package Lab.bank;

public class Bank extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bank.class.getName());
    Data_Base db = new Data_Base();

    /**
     * Creates new form Bank
     */
    public Bank() {
        initComponents();
        updateQueueDisplay();
        updateLoansQueueDisplay();
        updateAccountQueueDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void updateQueueDisplay() {

        int depositQueueCount = db.getSizeDepositQueue();
        showDepositeQueues.setText(String.valueOf(depositQueueCount));
    }

    public void updateLoansQueueDisplay() {

        int LoansQueuesCount = db.getSizeLoanQueue();
        ShowLoansQueues.setText(String.valueOf(LoansQueuesCount));
    }
    
    public void updateAccountQueueDisplay() {

        int AccountQueuesCount = db.getSizeAccounQueue();
        ShowAccountQueues.setText(String.valueOf(AccountQueuesCount));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        AddAccount_OpenningQueue = new javax.swing.JButton();
        AddLoansQueue = new javax.swing.JButton();
        AddDepositeQueue = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Deposites1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Deposites2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Deposites3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Loans = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Account = new javax.swing.JLabel();
        connect1 = new javax.swing.JButton();
        finnish1 = new javax.swing.JButton();
        connect2 = new javax.swing.JButton();
        finnish2 = new javax.swing.JButton();
        connect3 = new javax.swing.JButton();
        finnish3 = new javax.swing.JButton();
        connect4 = new javax.swing.JButton();
        finnish4 = new javax.swing.JButton();
        connect5 = new javax.swing.JButton();
        finnish5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        showDepositeQueues = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        ShowLoansQueues = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ShowAccountQueues = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddAccount_OpenningQueue.setText("Account Openning");
        AddAccount_OpenningQueue.addActionListener(this::AddAccount_OpenningQueueActionPerformed);

        AddLoansQueue.setText("Loans");
        AddLoansQueue.addActionListener(this::AddLoansQueueActionPerformed);

        AddDepositeQueue.setText("Deposite");
        AddDepositeQueue.addActionListener(this::AddDepositeQueueActionPerformed);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Deposites1.setText("Deposite");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(Deposites1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Deposites1)
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Deposites2.setText("Deposite");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(Deposites2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Deposites2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Deposites3.setText("Deposite");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Deposites3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Deposites3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Loans.setText("Loans");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Loans, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Loans)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Account.setText("Account Openning");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Account)
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Account)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        connect1.setText("connect");
        connect1.addActionListener(this::connect1ActionPerformed);

        finnish1.setText("Finnish");
        finnish1.addActionListener(this::finnish1ActionPerformed);

        connect2.setText("connect");
        connect2.addActionListener(this::connect2ActionPerformed);

        finnish2.setText("Finnish");
        finnish2.addActionListener(this::finnish2ActionPerformed);

        connect3.setText("connect");
        connect3.addActionListener(this::connect3ActionPerformed);

        finnish3.setText("Finnish");
        finnish3.addActionListener(this::finnish3ActionPerformed);

        connect4.setText("connect");
        connect4.addActionListener(this::connect4ActionPerformed);

        finnish4.setText("Finnish");
        finnish4.addActionListener(this::finnish4ActionPerformed);

        connect5.setText("connect");
        connect5.addActionListener(this::connect5ActionPerformed);

        finnish5.setText("Finnish");
        finnish5.addActionListener(this::finnish5ActionPerformed);

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        showDepositeQueues.setText("num");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(showDepositeQueues)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(showDepositeQueues)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ShowLoansQueues.setText("num");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(ShowLoansQueues)
                .addGap(84, 84, 84))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ShowLoansQueues)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ShowAccountQueues.setText("num");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(ShowAccountQueues)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ShowAccountQueues)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setText("Deposite Queues");

        jLabel2.setText("Loans Queues");

        jLabel3.setText("Account Openning Queues");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(connect1)
                        .addGap(28, 28, 28)
                        .addComponent(finnish1)
                        .addGap(40, 40, 40)
                        .addComponent(connect2)
                        .addGap(30, 30, 30)
                        .addComponent(finnish2)
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(connect3)
                        .addGap(36, 36, 36)
                        .addComponent(finnish3)
                        .addGap(74, 74, 74)
                        .addComponent(connect4)
                        .addGap(35, 35, 35)
                        .addComponent(finnish4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(connect5)
                        .addGap(46, 46, 46)
                        .addComponent(finnish5)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddLoansQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddAccount_OpenningQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddDepositeQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(connect1)
                            .addComponent(finnish2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(finnish1)
                                .addComponent(connect2))
                            .addComponent(connect4)
                            .addComponent(finnish4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(finnish5)
                                .addComponent(connect5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finnish3)
                            .addComponent(connect3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddDepositeQueue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddLoansQueue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddAccount_OpenningQueue)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>                        

    private void AddAccount_OpenningQueueActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        db.AddAccountNumberQueue();
        updateAccountQueueDisplay();


    }                                                        

    private void connect1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int counter1 = db.getNextDepositQueue();

        if (counter1 != -1) {
            System.out.println("====================");
            System.out.println("Call [" + counter1 + "] to counter Deposite1 :");
            Deposites1.setText("Deposite: " + counter1);
            connect1.setEnabled(false);
            updateQueueDisplay();
            System.out.println("====================");
            db.showdepositQueue();
            System.out.println(" ");
        } else {
            System.out.println("No accounts left in queue.");
            javax.swing.JOptionPane.showMessageDialog(this, "no have Queues");
        }

    }                                        

    private void finnish1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Deposites1.setText("Deposite");
        connect1.setEnabled(true);
    }                                        

    private void connect2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int counter2 = db.getNextDepositQueue();

        if (counter2 != -1) {
            System.out.println("====================");
            System.out.println("Call [" + counter2 + "] to counter Deposite2 :");
            Deposites2.setText("Deposite: " + counter2);
            System.out.println("====================");
            connect2.setEnabled(false);
            updateQueueDisplay();
            db.showdepositQueue();
            System.out.println(" ");
        } else {
            System.out.println("No accounts left in queue.");
            javax.swing.JOptionPane.showMessageDialog(this, "no have Queues");
        }
    }                                        

    private void finnish2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Deposites2.setText("Deposite");
        connect2.setEnabled(true);
    }                                        

    private void connect3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int counter3 = db.getNextDepositQueue();

        if (counter3 != -1) {
            System.out.println("====================");
            System.out.println("Call [" + counter3 + "] to counter Deposite3 :");
            Deposites3.setText("Deposite: " + counter3);
            connect3.setEnabled(false);
            updateQueueDisplay();
            System.out.println("====================");
            db.showdepositQueue();
            System.out.println(" ");
            
            
        } else {
            System.out.println("No accounts left in queue.");
            javax.swing.JOptionPane.showMessageDialog(this, "no have Queues");
        }
    }                                        

    private void finnish3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Deposites3.setText("Deposite");
        connect3.setEnabled(true);
    }                                        

    private void connect4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int counter4 = db.getNextLoanQueue();

        if (counter4 != -1) {
            System.out.println("====================");
            System.out.println("Call [" + counter4 + "] to counter Loans  :");
            Loans.setText("Loans: " + counter4);
            connect4.setEnabled(false);
            updateLoansQueueDisplay();
            System.out.println("====================");
            db.showloanQueue();
            System.out.println(" ");
        } else {
            System.out.println("No accounts left in queue.");
            javax.swing.JOptionPane.showMessageDialog(this, "no have Queues");
        }
    }                                        

    private void finnish4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Loans.setText("Loans");
        connect4.setEnabled(true);
    }                                        

    private void connect5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int counter5 = db.getNextAccountQueue();

        if (counter5 != -1) {
            System.out.println("====================");
            System.out.println("Call [" + counter5 + "] to counter Account :");
            Account.setText("Account: " + counter5);
            connect5.setEnabled(false);
            updateAccountQueueDisplay();
            System.out.println("====================");
            db.showAccountQueue();
            System.out.println(" ");
        } else {
            System.out.println("No accounts left in queue.");
            javax.swing.JOptionPane.showMessageDialog(this, "no have Queues");
            
        }
    }                                        

    private void finnish5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Account.setText("Account Openning");
        connect1.setEnabled(true);
    }                                        

    private void AddLoansQueueActionPerformed(java.awt.event.ActionEvent evt) {                                              
        db.AddLoanNumberQueue();
        updateLoansQueueDisplay();
    }                                             

    private void AddDepositeQueueActionPerformed(java.awt.event.ActionEvent evt) {                                                 

        db.AddDepositNumberQueue();
        updateQueueDisplay();


    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bank().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Account;
    private javax.swing.JButton AddAccount_OpenningQueue;
    private javax.swing.JButton AddDepositeQueue;
    private javax.swing.JButton AddLoansQueue;
    private javax.swing.JLabel Deposites1;
    private javax.swing.JLabel Deposites2;
    private javax.swing.JLabel Deposites3;
    private javax.swing.JLabel Loans;
    private javax.swing.JLabel ShowAccountQueues;
    private javax.swing.JLabel ShowLoansQueues;
    private javax.swing.JButton connect1;
    private javax.swing.JButton connect2;
    private javax.swing.JButton connect3;
    private javax.swing.JButton connect4;
    private javax.swing.JButton connect5;
    private javax.swing.JButton finnish1;
    private javax.swing.JButton finnish2;
    private javax.swing.JButton finnish3;
    private javax.swing.JButton finnish4;
    private javax.swing.JButton finnish5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel showDepositeQueues;
    // End of variables declaration                   
//<editor-fold defaultstate="collapsed" desc="comment">
}

//</editor-fold>


